name: Deploy Frontend to DEV environment

on:
  push:
    branches:
      - dev
    paths:
      - 'front-end/flutter/doctor_goblin/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter with FVM
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./front-end/flutter/doctor_goblin

      - name: Build Flutter web app
        run: flutter build web
        working-directory: ./front-end/flutter/doctor_goblin

      - name: Deploy to NAS-PC via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}:49152
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # PowerShell 스크립트로 실행
            $targetDir = "C:/tools/nginx-1.29.0/html/dev-app"
            $sourceDir = "/home/runner/work/doctor-goblin/doctor-goblin/front-end/flutter/doctor_goblin/build/web"

            # 기존 폴더 내용 삭제
            Remove-Item -Path $targetDir -Recurse -Force
            
            # 새로운 빌드 파일 복사
            Copy-Item -Path "$sourceDir/*" -Destination $targetDir -Recurse -Force

            # Nginx 재시작
            & "C:/tools/nginx-1.29.0/nginx.exe" -s reload